package com.cmcc.zysoft.schedule.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name="tb_c_holiday")
public class Holiday  implements java.io.Serializable {


	 private static final long serialVersionUID = 6381443392042172319L;
     private String holidayId;
     private String weekId;
     private Date day;
     private String type;
     private String holidayName;
     private String mark1;
     private String mark2;
     

    public Holiday() {
    }


	public Holiday(String holidayId, String weekId, Date day, String type,
			String holidayName, String mark1, String mark2) {
		this.holidayId = holidayId;
		this.weekId = weekId;
		this.day = day;
		this.type = type;
		this.holidayName = holidayName;
		this.mark1 = mark1;
		this.mark2 = mark2;
	}


	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="holiday_id", unique=true, nullable=false, length=32)
    public String getHolidayId() {
        return this.holidayId;
    }
    
    public void setHolidayId(String holidayId) {
        this.holidayId = holidayId;
    }
    
    @Column(name="week_id", length=32)
    public String getWeekId() {
		return weekId;
	}




	public void setWeekId(String weekId) {
		this.weekId = weekId;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="day")
	public Date getDay() {
		return day;
	}


	public void setDay(Date day) {
		this.day = day;
	}

	@Column(name="type", length=1)
	public String getType() {
		return type;
	}


	public void setType(String type) {
		this.type = type;
	}

	@Column(name="holiday_name", length=20)
	public String getHolidayName() {
		return holidayName;
	}


	public void setHolidayName(String holidayName) {
		this.holidayName = holidayName;
	}


	@Column(name="mark1", length=32)
	public String getMark1() {
		return mark1;
	}


	public void setMark1(String mark1) {
		this.mark1 = mark1;
	}

	@Column(name="mark2", length=32)
	public String getMark2() {
		return mark2;
	}


	public void setMark2(String mark2) {
		this.mark2 = mark2;
	}


}


