package com.cmcc.zysoft.schedule.model;

// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Schedule generated by hbm2java
 */
@Entity
@Table(name = "tb_c_schedule_commit")
public class ScheduleCommit implements java.io.Serializable {

	private static final long serialVersionUID = 6381443392042172318L;
	private String scheduleId;
	private String weekId;
	private String title;
	private Date startTime;
	private Date endTime;
	private String place;
	private String men;
	private String details;
	private String remark;
	private String type;
	private String createUser;
	private String createUserType;
	private Date createTime;
	private String modifyUser;
	private Date modifyTime;
	private String mark1;
	private String mark2;
	private String delFlag;

	public ScheduleCommit() {
	}

	public ScheduleCommit(String scheduleId, String weekId, String title,
			Date startTime, Date endTime, String place, String men,
			String details, String remark, String type, String createUser,
			String createUserType, Date createTime, String modifyUser,
			Date modifyTime, String mark1, String mark2) {
		this.scheduleId = scheduleId;
		this.weekId = weekId;
		this.title = title;
		this.startTime = startTime;
		this.endTime = endTime;
		this.place = place;
		this.men = men;
		this.details = details;
		this.remark = remark;
		this.type = type;
		this.createUser = createUser;
		this.createUserType = createUserType;
		this.createTime = createTime;
		this.modifyUser = modifyUser;
		this.modifyTime = modifyTime;
		this.mark1 = mark1;
		this.mark2 = mark2;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "schedule_id", unique = true, nullable = false, length = 32)
	public String getScheduleId() {
		return this.scheduleId;
	}

	public void setScheduleId(String scheduleId) {
		this.scheduleId = scheduleId;
	}

	@Column(name = "week_id", length = 32)
	public String getWeekId() {
		return weekId;
	}

	public void setWeekId(String weekId) {
		this.weekId = weekId;
	}

	@Column(name = "title", length = 100)
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "start_time")
	public Date getStartTime() {
		return startTime;
	}

	public void setStartTime(Date startTime) {
		this.startTime = startTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time")
	public Date getEndTime() {
		return endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "place", length = 100)
	public String getPlace() {
		return place;
	}

	public void setPlace(String place) {
		this.place = place;
	}

	@Column(name = "men", length = 50)
	public String getMen() {
		return men;
	}

	public void setMen(String men) {
		this.men = men;
	}

	@Column(name = "details", length = 600)
	public String getDetails() {
		return details;
	}

	public void setDetails(String details) {
		this.details = details;
	}

	@Column(name = "remark", length = 400)
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "type", length = 11)
	public String getType() {
		return type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "create_user_type", length = 11)
	public String getCreateUserType() {
		return createUserType;
	}

	public void setCreateUserType(String createUserType) {
		this.createUserType = createUserType;
	}

	@Column(name = "create_user", length = 32)
	public String getCreateUser() {
		return createUser;
	}

	public void setCreateUser(String createUser) {
		this.createUser = createUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time")
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Column(name = "modify_user", length = 32)
	public String getModifyUser() {
		return modifyUser;
	}

	public void setModifyUser(String modifyUser) {
		this.modifyUser = modifyUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "modify_time")
	public Date getModifyTime() {
		return modifyTime;
	}

	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	@Column(name = "mark1", length = 32)
	public String getMark1() {
		return mark1;
	}

	public void setMark1(String mark1) {
		this.mark1 = mark1;
	}

	@Column(name = "mark2", length = 32)
	public String getMark2() {
		return mark2;
	}

	public void setMark2(String mark2) {
		this.mark2 = mark2;
	}
	@Column(name = "del_flag", length = 11)
	public String getDelFlag() {
		return delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
}
