package com.cmcc.zysoft.schedule.model;

// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ScheduleLeader generated by hbm2java
 */
@Entity
@Table(name = "tb_c_schedule_release_leader")
public class ScheduleReleaseLeader implements java.io.Serializable {

	private static final long serialVersionUID = 6381443392042172327L;
	private String scheduleLeaderId;
	private String scheduleId;
	private int leaderId;
	private String delFlag;

	public ScheduleReleaseLeader() {
	}

	public ScheduleReleaseLeader(String scheduleLeaderId, String scheduleId,
			int leaderId) {
		this.scheduleLeaderId = scheduleLeaderId;
		this.scheduleId = scheduleId;
		this.leaderId = leaderId;
	}

	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "schedule_leader_id", unique = true, nullable = false, length = 32)
	public String getScheduleLeaderId() {
		return scheduleLeaderId;
	}

	public void setScheduleLeaderId(String scheduleLeaderId) {
		this.scheduleLeaderId = scheduleLeaderId;
	}

	@Column(name = "schedule_id", length = 32)
	public String getScheduleId() {
		return scheduleId;
	}

	public void setScheduleId(String scheduleId) {
		this.scheduleId = scheduleId;
	}

	@Column(name = "leader_id")
	public int getLeaderId() {
		return leaderId;
	}

	public void setLeaderId(int leaderId) {
		this.leaderId = leaderId;
	}
	@Column(name = "del_flag", length = 11)
	public String getDelFlag() {
		return delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
}
