package com.cmcc.zysoft.schedule.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;
import org.hibernate.annotations.GenericGenerator;



/**
 * SystemUser generated by hbm2java
 */
@Entity
@Table(name="tb_c_system_user")
@JsonIgnoreProperties(value={"hibernateLazyInitializer","handler","fieldHandler"}) 
public class SystemUser  implements java.io.Serializable {


	 private static final long serialVersionUID = 6381443392042172315L;
	 private String userId;
     private String userName;
     private String password;
     private String passSalt;
     private String mobile;
     private String realName;
     private Role role;
     private int disOrder;
     private Leader leader;
     private String delFlag;
     private String mark1;
     private String mark2;

    public SystemUser() {
    }

	
    public SystemUser(String userId) {
        this.userId = userId;
    }
    
    
   
    public SystemUser(String userId, String userName, String password,
			String passSalt, String mobile, String realName, Role role,
			int disOrder, Leader leader, String delFlag, String mark1, String mark2) {
		this.userId = userId;
		this.userName = userName;
		this.password = password;
		this.passSalt = passSalt;
		this.mobile = mobile;
		this.realName = realName;
		this.role = role;
		this.disOrder = disOrder;
		this.leader = leader;
		this.delFlag = delFlag;
		this.mark1 = mark1;
		this.mark2 = mark2;
	}


	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="user_id", unique=true, nullable=false, length=32)
    public String getUserId() {
        return this.userId;
    }
    
    public void setUserId(String userId) {
        this.userId = userId;
    }
    
    
    @Column(name="user_name", length=32)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="password", length=64)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="pass_salt", length=64)
    public String getPassSalt() {
        return this.passSalt;
    }
    
    public void setPassSalt(String passSalt) {
        this.passSalt = passSalt;
    }
    
    @Column(name="mobile", length=11)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name="real_name", length=32)
    public String getRealName() {
        return this.realName;
    }
    
    public void setRealName(String realName) {
        this.realName = realName;
    }
      
    @Column(name="del_flag", length=1)
    public String getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag;
    }
	@Column(name="dis_order")
	public int getDisOrder() {
		return disOrder;
	}


	public void setDisOrder(int disOrder) {
		this.disOrder = disOrder;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="role_id")
	public Role getRole() {
		return role;
	}


	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="leader_id")
	public Leader getLeader() {
		return leader;
	}


	public void setLeader(Leader leader) {
		this.leader = leader;
	}


	@Column(name="mark1", length=32)
	public String getMark1() {
		return mark1;
	}


	public void setMark1(String mark1) {
		this.mark1 = mark1;
	}

	@Column(name="mark2", length=32)
	public String getMark2() {
		return mark2;
	}


	public void setMark2(String mark2) {
		this.mark2 = mark2;
	}


}


