package com.cmcc.zysoft.schedule.model;
// Generated 2013-2-28 14:16:39 by Hibernate Tools 3.2.2.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Week generated by hbm2java
 */
@Entity
@Table(name="tb_c_week")
public class Week  implements java.io.Serializable {


	 private static final long serialVersionUID = 6381443392042172318L;
	 private String weekId;
     private Date weekStart;
     private String releaseTag;
     private Date releaseTime;
     private String mark1;
     private String mark2;
   
    public Week() {
    }

	public Week(String weekId, Date weekStart, String releaseTag,
			Date releaseTime, String mark1, String mark2) {
		this.weekId = weekId;
		this.weekStart = weekStart;
		this.releaseTag = releaseTag;
		this.releaseTime = releaseTime;
		this.mark1 = mark1;
		this.mark2 = mark2;
	}
	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Id
	@GeneratedValue(generator = "generator")
    @Column(name="week_id", unique=true, nullable=false, length=32)
	public String getWeekId() {
		return weekId;
	}

	public void setWeekId(String weekId) {
		this.weekId = weekId;
	}
	@Temporal(TemporalType.DATE)
	@Column(name="week_start")
	public Date getWeekStart() {
		return weekStart;
	}

	public void setWeekStart(Date weekStart) {
		this.weekStart = weekStart;
	}
	@Column(name="release_tag", length=11)
	public String getReleaseTag() {
		return releaseTag;
	}

	public void setReleaseTag(String releaseTag) {
		this.releaseTag = releaseTag;
	}
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="release_time")
	public Date getReleaseTime() {
		return releaseTime;
	}

	public void setReleaseTime(Date releaseTime) {
		this.releaseTime = releaseTime;
	}
	@Column(name="mark1", length=32)
	public String getMark1() {
		return mark1;
	}

	public void setMark1(String mark1) {
		this.mark1 = mark1;
	}
	@Column(name="mark2", length=32)
	public String getMark2() {
		return mark2;
	}

	public void setMark2(String mark2) {
		this.mark2 = mark2;
	}


	

}


